#!/bin/sh
export WINEDIR="$(dirname "$0")/usr"
export WINE="$WINEDIR/bin/wine"
export PATH="$WINEDIR/bin:$PATH"
export LD_LIBRARY_PATH="$WINEDIR/lib64:$WINEDIR/lib:$LD_LIBRARY_PATH"
[ ! -n "$1" ] && "$WINE" explorer||"$WINE" "$@"
